#!/bin/bash
#
#SBATCH --job-name=PeleC-2D-Channel-Planar-Detonation-Driver-Section-Simulation
#SBATCH --output=Pelec-Diagnostic-File-Restart.dat
#
#SBATCH --partition=long
#
#SBATCH --nodes=2                # node count
#SBATCH --ntasks-per-node=16      # number of tasks across for a single nods
#SBATCH --cpus-per-task=1        # cpu-cores per task (>1 if multi-threaded tasks)
#SBATCH --mem-per-cpu=16G        # memory per cpu-core
#
#SBATCH --time=7-00:00:00
#
#SBATCH --mail-type=begin        # send email when job begins
#SBATCH --mail-type=end          # send email when job ends
#SBATCH --mail-user=nadexterbrown@wpi.edu

srun --nodes=2 --ntasks-per-node=16 --mpi=pmi2 ./PeleC2d.gnu.MPI.ex example-simple.inp
